---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nacos-storage
  labels:
    app/component: nacos
    app/elasticsearch-role: nacos
provisioner: kubernetes.io/no-provisioner ## 静态（手动）创建的存储类,不会自动创建 PV
volumeBindingMode: WaitForFirstConsumer ## 延迟绑定模式,只有在 Pod 真的调度到某个节点上后，才绑定 PVC 对应的 PV
reclaimPolicy: Retain
allowVolumeExpansion: true
