---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacos-pv-data-0
  labels:
    app/component: nacos
    app/nacos-role: nacos
spec:
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: nacos-storage 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/nacos/pv-data-0
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname    ## 根据节点
              operator: In
              values: ["moone-worker-31"]

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacos-pv-data-1
  labels:
    app/component: nacos
    app/nacos-role: nacos
spec:
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: nacos-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/nacos/pv-data-1
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname    ## 根据节点
              operator: In
              values: ["moone-worker-32"]


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacos-pv-data-2
  labels:
    app/component: nacos
    app/nacos-role: nacos
spec:
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: nacos-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/nacos/pv-data-2
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname    ## 根据节点
              operator: In
              values: ["moone-worker-33"]
