apiVersion: v1
kind: Secret
metadata:
  name: nacos-secret
  namespace: devops
type: Opaque
data:
  MYSQL_SERVICE_USER: bmFjb3MK
  MYSQL_SERVICE_PASSWORD: bmFjb3MK
  MYSQL_SERVICE_DB_NAME: bmFjb3NfZGIK

  # nacos 鉴权 token
  NACOS_AUTH_TOKEN: SGg4S0pqOVlrQ2MrZzNoWlpTVEdHZmRjTEY3MC9tTlBjRmJubFltdjVicS9lOGNpL0NIa0dxNWY5SEt1d09zTQo= 
  NACOS_AUTH_IDENTITY_KEY: bmFjb3MK #Y3lwMms3SjdTV2lHNGcraWNpK2RodTE1eXdoOWpHSjJweTJFUEduZi9oRT0K
  NACOS_AUTH_IDENTITY_VALUE: bmFjb3MK #RkxQWFRMQTNzVTZrMXN2VFA5SkJyakhUQzQzcTBrNnFkSEhyMmFmVm82MD0K
