---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nacos-gw
  namespace: devops
spec:
  gatewayClassName: traefik
  listeners:
  - protocol: HTTP
    port: 80
    name: nacos-gw-http
    allowedRoutes:
      namespaces:
        from: All

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nacos-http
  namespace: devops
spec:
  hostnames: 
  - nacos.kubecy.com
  parentRefs:
  - name: nacos-gw
    #sectionName: http
    kind: Gateway
  rules:
  - backendRefs:
    - name: nacos-headless
      port: 8080
      kind: Service
    matches:
    - path:
        type: PathPrefix
        value: /
