---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: jenkins-gw
  namespace: devops
spec:
  gatewayClassName: traefik
  listeners:
  - protocol: HTTP
    port: 80
    name: jenkins-gw-http
    allowedRoutes:
      namespaces:
        from: All

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jenkins-http
  namespace: devops
spec:
  hostnames: 
  - jenkins.kubecy.cn
  parentRefs:
  - name: jenkins-gw
    #sectionName: http
    kind: Gateway
  rules:
  - backendRefs:
    - name: jenkins
      port: 8080
      kind: Service
    matches:
    - path:
        type: PathPrefix
        value: /
