---
apiVersion: v1
kind: Secret
metadata:
  name: sonar-sonarqube
  namespace: devops
  labels:
    app: sonarqube
    release: sonar
type: Opaque
data:
  jdbc-password: "c29uYXJwYXNzCg=="

---
apiVersion: v1
kind: Secret
metadata:
  name: sonar-sonarqube-monitoring-passcode
  namespace: devops
  labels:
    app: sonarqube
    release: sonar
type: Opaque
data:
  SONAR_WEB_SYSTEMPASSCODE: "ZGVmaW5lX2l0"

---
apiVersion: v1
kind: Secret
metadata:
  name: sonar-sonarqube-http-proxies
  namespace: devops
  labels:
    app: sonarqube
    release: sonar
type: Opaque
stringData:
  PLUGINS-HTTP-PROXY: ""
  PLUGINS-HTTPS-PROXY: ""
  PLUGINS-NO-PROXY: ""
  PROMETHEUS-EXPORTER-HTTP-PROXY: ""
  PROMETHEUS-EXPORTER-HTTPS-PROXY: ""
  PROMETHEUS-EXPORTER-NO-PROXY: ""
