---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-sonarqube
  labels:
    app: sonarqube
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/volume/sonarqube
    type: DirectoryOrCreate
  claimRef:
    kind: PersistentVolumeClaim
    namespace: devops
    name: sonarqube-data-pvc
    apiVersion: v1
