---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonar-sonarqube
  namespace: devops
spec:
  ingressClassName: "nginx"
  rules:
    - host: sonar.kubecy.com
      http:
        paths:
          - path: /                
            pathType: Prefix
            backend:
              service:
                name: sonar-sonarqube
                port:
                  number: 9000
