apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: sonar-gateway
  namespace: devops
spec:
  gatewayClassName: traefik 
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: sonar.kubecy.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sonar-route
  namespace: devops
spec:
  parentRefs:
    - name: sonar-gateway
      namespace: devops
  hostnames:
    - sonar.kubecy.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: sonar-sonarqube
          port: 9000

